version: '3.7'
services:

  velocity-template-tester:
    image: devatherock/velocity-template-tester:${DOCKER_TAG:-latest}
    container_name: velocity-template-tester-intg
    network_mode: "host"
    environment:
      JAVA_OPTS: ${JAVA_OPTS:--Xmx640m}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 2s
      timeout: 60s
      retries: 30
