slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:0.4.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD

orbs:
  docker: circleci/docker@1.5.0
  gradle: circleci/gradle@2.2.0
  heroku: circleci/heroku@1.0.1

work_directory: &work_directory
  working_directory: ~/velocity-template-tester

resource_class: &resource_class
  resource_class: small
  
executors:
  jdk-executor:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory
    environment:
      # To generate swagger UI
      JAVA_TOOL_OPTIONS: '-Dmicronaut.openapi.views.spec=swagger-ui.enabled=true,swagger-ui.theme=flattop'

version: 2.1
jobs:
  deploy:
    executor: heroku/default
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker
      - attach_workspace:
          at: ~/velocity-template-tester
      - run:
          name: Build and push the docker image to registry.heroku.com
          command: |
            docker build -t registry.heroku.com/velocity-template-tester/web -t devatherock/velocity-template-tester:native -f docker/Native.Dockerfile .
            heroku container:login
            docker push registry.heroku.com/velocity-template-tester/web
            heroku container:release -a velocity-template-tester web
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push devatherock/velocity-template-tester:native

  notify_success:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
    steps:
      - run: /bin/simpleslack -c "#33ad7f" || true
  notify_failure:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Failure: {{.CircleBuildUrl}} by {{.CircleUsername}}"
    steps:
      - run:
          name: Failure notification
          command: /bin/simpleslack -c "#a1040c" || true
          when: on_fail

workflows:
  version: 2.1
  build_publish:
    jobs:
      - gradle/run:
          executor: jdk-executor
          context:
            - docker-credentials
          filters:
            branches:
              only: master
          post-steps:
            - persist_to_workspace:
                root: ~/velocity-template-tester
                paths:
                  - build
      - docker/publish:
          executor: jdk-executor
          context:
            - docker-credentials
          requires:
            - gradle/run
          image: devatherock/velocity-template-tester  
          attach-at: ~/velocity-template-tester
          tag: "0.6.1,latest"
          use-remote-docker: true
          docker-username: DOCKER_USERNAME
          dockerfile: docker/Jar.Dockerfile
      - deploy:
          context:
            - docker-credentials
            - heroku-credentials
          requires:
            - gradle/run
      - notify_success:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - docker/publish
            - deploy
      - notify_failure:
          context:
            - docker-credentials
            - slack-webhook 
          requires:
            - docker/publish
            - deploy
  pr_check:
    jobs:
      - gradle/run:
          executor: jdk-executor
          context:
            - docker-credentials
          filters:
            branches:
              ignore: master
