work_directory: &work_directory
  working_directory: ~/velocity-template-tester

jdk_image: &jdk_image
  docker:
    - image: circleci/openjdk:11-jdk

orbs:
  heroku: circleci/heroku@1.0.1

version: 2.1
jobs:
  test:
    <<: *jdk_image
    <<: *work_directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: |
          ./gradlew build
  build:
    <<: *jdk_image
    environment:
      # To generate swagger UI
      JAVA_TOOL_OPTIONS: '-Dmicronaut.openapi.views.spec=swagger-ui.enabled=true,swagger-ui.theme=flattop'
    <<: *work_directory
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: ./gradlew build --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: ~/velocity-template-tester
          paths:
            - build
  publish:
    docker:
      - image: docker:19.03.6
    <<: *work_directory
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/velocity-template-tester
      - run: |
          TAG=0.5.0
          docker build -t devatherock/velocity-template-tester:$TAG -t devatherock/velocity-template-tester:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/velocity-template-tester:$TAG
          docker push devatherock/velocity-template-tester:latest
  deploy:
    executor: heroku/default
    <<: *work_directory
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker
      - attach_workspace:
          at: ~/velocity-template-tester
      - run:
          name: Build and push the docker image to registry.heroku.com
          command: |
            docker build -t registry.heroku.com/velocity-template-tester/web .
            heroku container:login
            docker push registry.heroku.com/velocity-template-tester/web
            heroku container:release -a velocity-template-tester web

workflows:
  version: 2
  build_publish:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
      - deploy:
          requires:
            - build
  pr_check:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
