slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:0.7.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD

orbs:
  docker: circleci/docker@2.1.1
  heroku: circleci/heroku@1.2.6

work_directory: &work_directory
  working_directory: ~/velocity-template-tester

resource_class: &resource_class
  resource_class: small
  
release_filter: &release_filter
  filters:
    branches:
      only: non-existent-branch
    tags:
      only: /^v[0-9\.]+$/
      
pr_filter: &pr_filter
  filters:
    branches:
      ignore: master
  
executors:
  jdk-executor:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory
    environment:
      # To generate swagger UI
      JAVA_TOOL_OPTIONS: '-Dmicronaut.openapi.views.spec=swagger-ui.enabled=true,swagger-ui.theme=flattop'

version: 2.1
jobs:
  changelog_updater:
    docker:
    - image: devatherock/changelog-updater:latest
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    <<: *resource_class
    environment:
      VELA_BUILD_AUTHOR_EMAIL: "bot@renovateapp.com"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4a:86:fe:0e:c3:0e:ad:0d:1d:5c:3e:48:cf:28:39:5d"
      - checkout
      - run: sh /scripts/entry-point.sh

  test:
    executor: jdk-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/velocity-template-tester
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies
      - run: |
          ./gradlew test sonarqube -Dsonar.login=$SONAR_TOKEN
      - store_test_results:
          path: build/test-results
          
  add_timestamp_to_static_files:
    executor: jdk-executor
    <<: *work_directory
    steps:
      - checkout
      - run: sh build_time.sh
      - persist_to_workspace:
          root: ~/velocity-template-tester
          paths:
            - src/main/resources/public
          
  minify_js:
    docker:
      - image: devatherock/minify-js:1.0.3
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory
    environment:
      PARAMETER_INPUT_PATH: src/main/resources/public
      PARAMETER_ADD_SUFFIX: false
    steps:
      - checkout
      - attach_workspace:
          at: ~/velocity-template-tester
      - run: sh /entrypoint.sh
      - persist_to_workspace:
          root: ~/velocity-template-tester
          paths:
            - src/main/resources/public

  build:
    executor: jdk-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/velocity-template-tester
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies
      - run: |
          ./gradlew build sonarqube -Dsonar.login=$SONAR_TOKEN
      - persist_to_workspace:
          root: ~/velocity-template-tester
          paths:
            - build
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
          
  publish_release:
    executor: jdk-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/velocity-template-tester
      - run: |
          TAG=${CIRCLE_TAG#v}
          DEV_TAG=${CIRCLE_SHA1:0:8}
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker pull devatherock/velocity-template-tester:$DEV_TAG
          docker tag devatherock/velocity-template-tester:$DEV_TAG devatherock/velocity-template-tester:$TAG
          docker push devatherock/velocity-template-tester:$TAG

  deploy:
    executor: heroku/default
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker
      - attach_workspace:
          at: ~/velocity-template-tester
      - run:
          name: Build and push the docker image to registry.heroku.com
          command: |
            TAG=${CIRCLE_TAG#v}
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker pull devatherock/velocity-template-tester:$TAG
            docker tag devatherock/velocity-template-tester:$TAG registry.heroku.com/velocity-template-tester/web
            heroku container:login
            docker push registry.heroku.com/velocity-template-tester/web
            heroku container:release -a velocity-template-tester web

  notify:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run: /bin/simpleslack -c "#33ad7f" || true

workflows:
  version: 2.1
  build_publish:
    jobs:
      - add_timestamp_to_static_files:
          context:
            - docker-credentials
          filters:
            branches:
              only: master
      - minify_js:
          context:
            - docker-credentials
          requires:
            - add_timestamp_to_static_files
      - build:
          context:
            - docker-credentials
            - sonar-credentials
          requires:
            - minify_js
      - docker/publish:
          name: publish
          executor: jdk-executor
          context:
            - docker-credentials
          requires:
            - build
          image: devatherock/velocity-template-tester  
          attach-at: ~/velocity-template-tester
          tag: "${CIRCLE_SHA1:0:8},latest"
          use-remote-docker: true
          docker-username: DOCKER_USERNAME
          dockerfile: docker/Dockerfile
      - notify:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - publish
            
  release:
    jobs:
      - publish_release:
          context:
            - docker-credentials
          <<: *release_filter
      - deploy:
          context:
            - docker-credentials
            - heroku-credentials
          <<: *release_filter  
          requires:
            - publish_release
      - notify:
          context:
            - docker-credentials
            - slack-webhook
          <<: *release_filter  
          requires:
            - deploy
            
  pr_check:
    jobs:
      - changelog_updater:
          context:
            - docker-credentials
            - changelog-updater-credentials
          <<: *pr_filter
      - test:
          context:
            - docker-credentials
            - sonar-credentials
          <<: *pr_filter
          requires:
            - changelog_updater
